### ISSUE TITLE
docker: Error response from daemon: pull access denied for iclips, 

### ISSUE THREAD

**Issue by dogweather** [noxdafox/iclips#12]
The full error message is:

```
docker: Error response from daemon: pull access denied for iclips, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
```

**Comment by noxdafox** [comment]
Hello,

I am not so sure what is the root cause for this. What were you trying to do?

**Comment by dogweather** [comment]
I get this when running any of the three Docker examples in the Readme. I'm just looking for an easy way to test the app.

**Comment by noxdafox** [comment]
Did you build the container first?

**Comment by dogweather** [comment]
No, this isn't a published image, I guess you're saying?

**Comment by noxdafox** [comment]
I do not have a Docker Hub account hence the image is not published there. There might be some unofficial images uploaded there.

You can build the container locally as per the instruction in the README.
