### ISSUE TITLE
Multi-line entry in Jupyter Console cannot end % magic

### ISSUE THREAD

**Issue by rhpoon** [noxdafox/iclips#5]
I tried two pieces of given  sample code for i. %% define-python-function and ii. %% python and find that Enter twice does not execute the code, and the multi-line entry can't break.  Maybe a  Jupyter Console (6.2.)) bug or compatibility. Seems fine for non-magic codes.

Ritchie

**Comment by noxdafox** [comment]
I just tested it on my workstation and it works.

What OS are you using?

**Comment by rhpoon** [comment]
Windows with venv and  Python 3.6.3, I am trying linux venv. I am trying linux to see if it works

**Comment by rhpoon** [comment]
Hi i just retest on Ubuntu 16.04 python 3.7 venv and it works... Not sure if it is Windows or Python problem.
(however  i have problem setting up iclips venv / running it on python 3.5)

**Comment by rhpoon** [comment]
Also tested on Ubuntu  venv py3.5 ok..

**Comment by noxdafox** [comment]
`iCLIPS` bundles `clipspy` which is a `cffi` based library depending on C `libclips`. It is not so trivial to install from scratch as some knowledge regarding the domain might be necessary.

The recommendation is to run `iCLIPS` from its [docker-container](https://github.com/noxdafox/iclips#docker-container). This should solve most of the installation challenges on Linux.

I will try to grab a copy of Windows and spin `iCLIPS` on it. My blind guess is that magic methods on Windows do not work same as on Linux. Nevertheless, I am not sure this is a problem of `iCLIPS` or of Jupyter itself.

**Comment by noxdafox** [comment]
This was indeed a bug. The kernel was expecting the line separator to be OS specific one (in Windows it's `\r\n`) but the Jupyter console was sending UNIX line separator (`\n`).

Hence, the double line separator test was failing.

Thanks for reporting this and sorry for taking this long.

The bug is fixed since `0.2.5`.
