### ISSUE TITLE
Download as CLIPS (clp) file gives error

### ISSUE THREAD

**Issue by bsweileh** [noxdafox/iclips#7]
Hello,

When trying to download the Jupyter notebook as a CLIPS file via "File -> Download As -> CLIPS (clp)",  I get the following error on a browser new tab: 

> 500 : Internal Server Error
> The error was:
> nbconvert failed: FileExtension trait 'file_extension' does not begin with a dot: 'clp' 
> 

Please advise. Thanks!

**Comment by noxdafox** [comment]
Fixed in `0.2.2`. Thanks for reporting this!
