### ISSUE TITLE
Tab Autocompletion initially works but apparently stops working after running Jupyter notebook cells that generate output

### ISSUE THREAD

**Issue by bsweileh** [noxdafox/iclips#9]
Hi,

I have noticed that tab autocompletion in iCLIPS works when the CLIPS kernel starts, but as soon as I run a cell that generates some sort of output, the tab autocompletion no longer works. 

To reproduce:
1) type the command (facts) in Cell 1  --> you will notice that tab autocompletion works
2) run Cell 1 with shift+enter -> no output is produced
3) type the command (assert (number-list 1 2 3)) in Cell 2 -> you will notice that tab autocompletion still works
4) run Cell 2 with shift+enter -> output "(number-list 1 2 3)" is produced 
5) type the command (facts) in Cell 3  --> you will notice that tab autocompletion does not work any more
6) shutdown then restart the CLIPS kernel
7) type the command (assert (number-list 4 5 6)) in Cell 4 --> you will notice that tab autocompletion works
8) run Cell 4 with shift+enter -> output "(number-list 4 5 6)" is produced 
9) type the command (facts) in Cell 5  --> you will notice that tab autocompletion does not work any more

Please advise. Thanks!

**Comment by noxdafox** [comment]
Issue fixed in release `0.2.3`.
